# Generated by Django 3.2.7 on 2021-09-23 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210922_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='articles description', max_length=250, verbose_name='توصیفات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='articles title', max_length=50, verbose_name='نینر'),
        ),
    ]
